Repository oceanbase/ob-operator, pull requests merged in 2024-12, with the labels that each got.

#661 Docs: Added new architecture diagram and update related docs
  README-CN.md
  README.md
  docsite/docs/developer/arch.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/developer/arch.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-pages/index.md
  docsite/src/pages/index.md
  docsite/static/img/ob-operator-arch.png
  docsite/static/img/ob-operator-task-manager-arch.png
Labels: documentation

#678 Docs: replace specific versions of releases with stable
  README-CN.md
  README.md
  docsite/docs/dashboard/quickstart.mdx
  docsite/docs/developer/deploy-locally.md
  docsite/docs/developer/deploy.md
  docsite/docs/manual/200.quick-start-of-ob-operator.md
  docsite/docs/manual/300.deploy-ob-operator.md
  docsite/docs/manual/400.ob-operator-upgrade.md
  docsite/docs/manual/500.ob-operator-user-guide/200.tenant-management-of-ob-operator/100.create-tenant.md
  docsite/docs/manual/500.ob-operator-user-guide/200.tenant-management-of-ob-operator/300.delete-tenant-of-ob-operator.md
  docsite/docs/manual/900.appendix/100.example.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/dashboard/quickstart.mdx
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/developer/deploy-locally.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/developer/deploy.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/manual/200.quick-start-of-ob-operator.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/manual/300.deploy-ob-operator.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/manual/400.ob-operator-upgrade.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/manual/500.ob-operator-user-guide/200.tenant-management-of-ob-operator/100.create-tenant.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/manual/500.ob-operator-user-guide/200.tenant-management-of-ob-operator/300.delete-tenant-of-ob-operator.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/manual/900.appendix/100.example.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-pages/index.md
  docsite/src/pages/index.md
Labels: documentation

#693 docs(cli): added a new method to install ob-operator by okctl
  README-CN.md
  README.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-pages/index.md
  docsite/src/pages/index.md
  scripts/install-okctl.sh
Labels: documentation

#694 ds033 bugfix in cluster
  ui/src/components/SelectWithTooltip/index.tsx
  ui/src/components/TopoComponent/index.tsx
  ui/src/constants/index.ts
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Cluster/Detail/Overview/index.tsx
  ui/src/pages/Cluster/New/Topo.tsx
  ui/src/pages/Overview/NodesTable.tsx
  ui/src/pages/Tenant/Detail/Overview/BasicInfo.tsx
Labels: bug

#698 feat(topology): display topology configurations
  ui/src/constants/index.ts
  ui/src/pages/Cluster/Detail/Overview/BasicInfo.tsx
Labels: dashboard

#699 ds033 bugsfix in cluster
  ui/src/components/TopoComponent/G6register.tsx
  ui/src/components/TopoComponent/helper.ts
  ui/src/components/TopoComponent/index.tsx
  ui/src/pages/Cluster/Detail/Overview/index.tsx
  ui/src/pages/Cluster/New/Topo.tsx
  ui/src/pages/Cluster/New/index.tsx
  ui/src/pages/Tenant/Detail/NewBackup/index.tsx
Labels: bug
