Repository oceanbase/ob-operator, pull requests merged in 2024-04, with the labels that each got.

#277 Refactor url structure
  ui/config/routes.ts
  ui/src/components/TopoComponent/index.tsx
  ui/src/components/customModal/ActivateTenantModal.tsx
  ui/src/components/customModal/AddZoneModal.tsx
  ui/src/components/customModal/LogReplayModal.tsx
  ui/src/components/customModal/ModifyPasswordModal.tsx
  ui/src/components/customModal/ModifyUnitDetailModal.tsx
  ui/src/components/customModal/ModifyUnitModal.tsx
  ui/src/components/customModal/ScaleModal.tsx
  ui/src/components/customModal/SwitchTenantModal.tsx
  ui/src/components/customModal/UpgradeModal.tsx
  ui/src/components/customModal/UpgradeTenantModal.tsx
  ui/src/pages/Cluster/ClusterList.tsx
  ui/src/pages/Cluster/Detail/Monitor/index.tsx
  ui/src/pages/Cluster/Detail/Overview/ZoneTable.tsx
  ui/src/pages/Cluster/Detail/Overview/helper.ts
  ui/src/pages/Cluster/Detail/Overview/index.tsx
  ui/src/pages/Cluster/Detail/Tenant/index.tsx
  ui/src/pages/Cluster/Detail/index.tsx
  ui/src/pages/Tenant/Detail/Backup/BackupConfiguration.tsx
  ui/src/pages/Tenant/Detail/Backup/BackupJobs.tsx
  ui/src/pages/Tenant/Detail/Backup/index.tsx
  ui/src/pages/Tenant/Detail/Monitor/index.tsx
  ui/src/pages/Tenant/Detail/NewBackup/index.tsx
  ui/src/pages/Tenant/Detail/Overview/Replicas.tsx
  ui/src/pages/Tenant/Detail/Overview/index.tsx
  ui/src/pages/Tenant/Detail/Topo/index.tsx
  ui/src/pages/Tenant/Detail/index.tsx
  ui/src/pages/Tenant/TenantsList.tsx
Labels: dashboard

#279 Fix resource pool related defects
  ui/src/components/TopoComponent/constants.ts
  ui/src/components/TopoComponent/index.tsx
  ui/src/components/customModal/ModifyUnitDetailModal.tsx
  ui/src/hook/usePublicKey.ts
  ui/src/models/global.ts
  ui/src/pages/Tenant/Detail/Topo/index.tsx
  ui/src/pages/Tenant/helper.ts
  ui/src/utils/helper.ts
Labels: dashboard

#281 Some field adjustments
  ui/src/components/customModal/ModifyUnitModal.tsx
  ui/src/pages/Cluster/ClusterList.tsx
  ui/src/pages/Tenant/Detail/Backup/BackupConfiguration.tsx
  ui/src/pages/Tenant/Detail/Backup/index.tsx
  ui/src/pages/Tenant/Detail/NewBackup/AdvancedConfiguration.tsx
  ui/src/pages/Tenant/Detail/NewBackup/index.tsx
Labels: dashboard

#282 Add loading status
  ui/src/components/EventsTable/index.tsx
  ui/src/components/TopoComponent/index.less
  ui/src/components/TopoComponent/index.tsx
  ui/src/pages/Cluster/ClusterList.tsx
  ui/src/pages/Cluster/New/BasicInfo.tsx
  ui/src/pages/Cluster/New/index.tsx
  ui/src/pages/Cluster/index.tsx
  ui/src/pages/Overview/NodesTable.tsx
  ui/src/pages/Tenant/Detail/Backup/index.tsx
  ui/src/pages/Tenant/Detail/Overview/Backups.tsx
  ui/src/pages/Tenant/Detail/Overview/BasicInfo.tsx
  ui/src/pages/Tenant/Detail/Overview/index.tsx
  ui/src/pages/Tenant/Detail/Topo/index.tsx
Labels: dashboard

#283 fix:Refresh tooltip content
  ui/src/components/TopoComponent/helper.ts
  ui/src/components/TopoComponent/index.tsx
  ui/src/components/customModal/AddZoneModal.tsx
  ui/src/components/customModal/LogReplayModal.tsx
  ui/src/components/customModal/ModifyPasswordModal.tsx
  ui/src/components/customModal/ModifyUnitDetailModal.tsx
  ui/src/components/customModal/ScaleModal.tsx
  ui/src/components/customModal/SwitchTenantModal.tsx
  ui/src/components/customModal/UpgradeModal.tsx
  ui/src/constants/index.ts
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Cluster/ClusterList.tsx
  ui/src/pages/Cluster/Detail/Overview/BasicInfo.tsx
  ui/src/pages/Tenant/New/TenantSource.tsx
  ui/src/services/typings.d.ts
Labels: dashboard

#284 Optimize the style of status detail
  ui/src/pages/Cluster/ClusterList.tsx
  ui/src/pages/Cluster/Detail/Overview/BasicInfo.tsx
  ui/src/pages/Cluster/Detail/Overview/ZoneTable.tsx
Labels: dashboard

#286 fix:Computing resources
  ui/src/pages/Cluster/ClusterList.tsx
  ui/src/pages/Cluster/Detail/Overview/BasicInfo.tsx
  ui/src/pages/Tenant/helper.ts
Labels: bug, dashboard

#287 Replace reported parameters
  ui/src/services/reportRequest/index.ts
  ui/src/services/typings.d.ts
  ui/src/utils/helper.ts
Labels: dashboard

#289 fix:Limit selecting cluster
  ui/src/components/customModal/ModifyUnitDetailModal.tsx
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Tenant/Detail/Overview/Replicas.tsx
  ui/src/pages/Tenant/Detail/Overview/index.tsx
  ui/src/pages/Tenant/New/BasicInfo.tsx
Labels: dashboard

#264 Feat: support terminal connection by handling websocket connection
  build/Dockerfile.dashboard
  go.mod
  go.sum
  internal/dashboard/business/k8s/exec.go
  internal/dashboard/generated/swagger/docs.go
  internal/dashboard/generated/swagger/swagger.json
  internal/dashboard/generated/swagger/swagger.yaml
  internal/dashboard/handler/conn_handler.go
  internal/dashboard/model/response/connection.go
  internal/dashboard/router/router.go
  internal/dashboard/router/v1/conn_router.go
Labels: dashboard

#280 Feat: terminal connection integration
  ui/config/routes.ts
  ui/package.json
  ui/src/components/Terminal/terminal.tsx
  ui/src/pages/Cluster/Detail/Connection/index.tsx
  ui/src/pages/Cluster/Detail/index.tsx
  ui/src/pages/Tenant/Detail/Connection/index.tsx
  ui/src/pages/Tenant/Detail/index.tsx
  ui/yarn.lock
Labels: dashboard

#292 fix:Correct the way resources are obtained
  ui/src/pages/Tenant/helper.ts
  ui/src/services/index.ts
Labels: bug

#296 Optimize style
  ui/src/components/PasswordInput/index.tsx
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Tenant/Detail/NewBackup/AdvancedConfiguration.tsx
  ui/src/pages/Tenant/Detail/NewBackup/BakMethodsList.tsx
  ui/src/pages/Tenant/Detail/NewBackup/index.less
Labels: dashboard

#294 Some usability optimizations
  ui/src/components/customModal/ModifyUnitDetailModal.tsx
  ui/src/pages/Tenant/Detail/Overview/index.tsx
  ui/src/pages/Tenant/ZoneItem/index.tsx
  ui/src/services/index.ts
  ui/src/utils/helper.ts
Labels: dashboard

#297 Accurately translate text and add header
  ui/package.json
  ui/src/components/MonitorComp/index.less
  ui/src/components/MonitorComp/index.tsx
  ui/src/components/MonitorDetail/DataFilter.tsx
  ui/src/components/MonitorDetail/index.less
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Cluster/ClusterList.tsx
  ui/src/pages/Cluster/Detail/Overview/BasicInfo.tsx
  ui/src/pages/Cluster/Detail/Overview/ServerTable.tsx
  ui/src/pages/Cluster/Detail/Overview/ZoneTable.tsx
  ui/src/pages/Cluster/Detail/Overview/index.tsx
  ui/src/pages/Cluster/index.less
  ui/src/pages/Cluster/index.tsx
  ui/src/pages/Overview/NodesTable.tsx
  ui/src/pages/Tenant/Detail/NewBackup/AdvancedConfiguration.tsx
  ui/src/pages/Tenant/Detail/NewBackup/SchduleSelectFormItem.tsx
  ui/src/pages/Tenant/Detail/Overview/BasicInfo.tsx
  ui/src/pages/Tenant/TenantsList.tsx
  ui/src/pages/Tenant/ZoneItem/index.tsx
  ui/src/pages/Tenant/index.less
Labels: dashboard

#311 Fix tenant select
  ui/src/pages/Cluster/Detail/Tenant/index.tsx
  ui/src/pages/Tenant/Detail/Overview/Backups.tsx
  ui/src/pages/Tenant/New/TenantSource.tsx
  ui/src/pages/Tenant/New/index.tsx
  ui/src/services/tenant.ts
  ui/yarn.lock
Labels: dashboard

#320 fix:Get tenants
  ui/src/constants/index.ts
  ui/src/pages/Cluster/ClusterList.tsx
  ui/src/pages/Tenant/New/BasicInfo.tsx
  ui/src/pages/Tenant/TenantsList.tsx
  ui/src/services/tenant.ts
Labels: dashboard

#322 Fixed Tenant Connection and Node IP Display
  internal/dashboard/business/oceanbase/obcluster.go
  internal/dashboard/handler/conn_handler.go
  internal/dashboard/handler/helper.go
Labels: dashboard

#336 i18n
  ui/src/components/Terminal/terminal.tsx
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Cluster/Detail/Connection/index.tsx
  ui/src/pages/Cluster/Detail/index.tsx
  ui/src/pages/Tenant/Detail/Connection/index.tsx
  ui/src/pages/Tenant/Detail/index.tsx
Labels: dashboard

#346 fix:The selected cluster exception display zone
  ui/src/pages/Tenant/New/BasicInfo.tsx
  ui/src/pages/Tenant/New/ResourcePools.tsx
  ui/src/pages/Tenant/New/index.tsx
  ui/src/pages/Tenant/helper.ts
  ui/src/services/index.ts
  ui/src/type/typings.d.ts
Labels: bug, dashboard
