Repository oceanbase/ob-operator, pull requests merged in 2024-08, with the labels that each got.

#500 Feat access control
  ui/config/config.ts
  ui/config/routes.ts
  ui/src/access.ts
  ui/src/app.tsx
  ui/src/components/TopoComponent/G6register.tsx
  ui/src/components/TopoComponent/index.tsx
  ui/src/components/customModal/HandleAccountModal.tsx
  ui/src/components/customModal/HandleRoleModal.tsx
  ui/src/pages/Access/Accounts.tsx
  ui/src/pages/Access/Roles.tsx
  ui/src/pages/Access/index.tsx
  ui/src/pages/Alert/Channel/index.tsx
  ui/src/pages/Alert/Event/index.tsx
  ui/src/pages/Alert/Rules/index.tsx
  ui/src/pages/Alert/Shield/index.tsx
  ui/src/pages/Alert/Subscriptions/index.tsx
  ui/src/pages/Cluster/ClusterList.tsx
  ui/src/pages/Cluster/Detail/Connection/index.tsx
  ui/src/pages/Cluster/Detail/Overview/ServerTable.tsx
  ui/src/pages/Cluster/Detail/Overview/ZoneTable.tsx
  ui/src/pages/Cluster/Detail/Overview/index.tsx
  ui/src/pages/Cluster/New/BasicInfo.tsx
  ui/src/pages/Cluster/New/Observer.tsx
  ui/src/pages/Cluster/index.tsx
  ui/src/pages/Layouts/BasicLayout/index.tsx
  ui/src/pages/Layouts/DetailLayout/index.tsx
  ui/src/pages/Login/index.tsx
  ui/src/pages/OBProxy/ClusterList.tsx
  ui/src/pages/OBProxy/Detail/Overview/DetailConfig.tsx
  ui/src/pages/OBProxy/Detail/Overview/index.tsx
  ui/src/pages/Overview/OverviewStatus.tsx
  ui/src/pages/Overview/index.tsx
  ui/src/pages/Tenant/TenantsList.tsx
  ui/src/pages/Tenant/index.tsx
  ui/src/utils/helper.ts
Labels: dashboard

#502 Added documents for 2.2.2 release
  docsite/docs/manual/500.ob-operator-user-guide/100.cluster-management-of-ob-operator/200.create-cluster.md
  docsite/docs/manual/500.ob-operator-user-guide/100.cluster-management-of-ob-operator/650.update-resources.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/manual/500.ob-operator-user-guide/100.cluster-management-of-ob-operator/200.create-cluster.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/manual/500.ob-operator-user-guide/100.cluster-management-of-ob-operator/650.update-resources.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-pages/changelog.md
  docsite/src/pages/changelog.md
Labels: documentation

#509 feat:reset password
  ui/config/routes.ts
  ui/src/api/errorHandling.ts
  ui/src/api/generated/api.ts
  ui/src/api/index.ts
  ui/src/app.tsx
  ui/src/components/customModal/HandleAccountModal.tsx
  ui/src/components/customModal/ResetPwdModal.tsx
  ui/src/pages/Access/Accounts.tsx
  ui/src/pages/Layouts/BasicLayout/index.tsx
  ui/src/pages/Layouts/index.tsx
  ui/src/pages/ResetPwd/index.less
  ui/src/pages/ResetPwd/index.tsx
Labels: dashboard

#517 Replace doc search index with an operator-specific one
  docsite/docusaurus.config.ts
Labels: documentation

#519 dashboard0.3.0 bugfix
  ui/src/components/customModal/ModifyUnitDetailModal.tsx
  ui/src/components/customModal/ScaleModal.tsx
  ui/src/constants/index.ts
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Tenant/Detail/Overview/Replicas.tsx
  ui/src/pages/Tenant/Detail/Overview/index.tsx
  ui/src/pages/Tenant/helper.ts
  ui/src/services/tenant.ts
Labels: bug, dashboard

#520 replenish policies
  ui/src/components/customModal/HandleAccountModal.tsx
  ui/src/components/customModal/HandleRoleModal.tsx
Labels: bug, dashboard

#523 modify unit
  ui/src/pages/Cluster/Detail/Overview/BasicInfo.tsx
Labels: bug, dashboard

#522 Enforce read permission if write permission is on
  internal/dashboard/business/ac/ac_suite_test.go
  internal/dashboard/business/ac/account_test.go
  internal/dashboard/business/ac/rbac.go
  internal/dashboard/business/ac/role_test.go
Labels: dashboard

#525 Some bugfix
  ui/src/components/customModal/HandleAccountModal.tsx
  ui/src/components/customModal/HandleRoleModal.tsx
  ui/src/components/customModal/ResetPwdModal.tsx
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Access/Accounts.tsx
  ui/src/pages/Access/Roles.tsx
  ui/src/pages/Access/index.tsx
  ui/src/pages/Overview/index.tsx
Labels: bug, dashboard

#528 Optimize CustomModal
  ui/src/components/customModal/ActivateTenantModal.tsx
  ui/src/components/customModal/AddNSModal.tsx
  ui/src/components/customModal/AddZoneModal.tsx
  ui/src/components/customModal/HandleAccountModal.tsx
  ui/src/components/customModal/HandleRoleModal.tsx
  ui/src/components/customModal/LogReplayModal.tsx
  ui/src/components/customModal/ModifyPasswordModal.tsx
  ui/src/components/customModal/ModifyUnitDetailModal.tsx
  ui/src/components/customModal/ModifyUnitModal.tsx
  ui/src/components/customModal/MyInfoModal.tsx
  ui/src/components/customModal/ResetPwdModal.tsx
  ui/src/components/customModal/ScaleModal.tsx
  ui/src/components/customModal/SwitchTenantModal.tsx
  ui/src/components/customModal/UpgradeModal.tsx
  ui/src/components/customModal/UpgradeTenantModal.tsx
  ui/src/components/customModal/index.tsx
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Access/Accounts.tsx
  ui/src/pages/Access/Roles.tsx
  ui/src/pages/Layouts/BasicLayout/index.tsx
  ui/src/pages/Login/index.tsx
Labels: dashboard

#536 When the role is modified, update the permissions
  ui/src/components/customModal/HandleRoleModal.tsx
Labels: bug, dashboard

#538 Some details
  ui/src/api/errorHandling.ts
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Access/Accounts.tsx
  ui/src/pages/Login/index.tsx
Labels: dashboard

#539 Reset form value after creating a role
  ui/src/components/customModal/HandleRoleModal.tsx
Labels: bug, dashboard
