Repository oceanbase/ob-operator, pull requests merged in 2024-05, with the labels that each got.

#356 Added promise wrapper to modify AxiosResponse to raw response
  ui/src/api/index.ts
Labels: dashboard

#354 Added UI for configuring forms and tables
  ui/src/api/generated/api.ts
  ui/src/api/generated/base.ts
  ui/src/api/index.ts
  ui/src/components/AlertDrawer/index.less
  ui/src/components/AlertDrawer/index.tsx
  ui/src/components/InputLabel/index.tsx
  ui/src/constants/index.ts
  ui/src/pages/Alert/AlarmFilter/index.tsx
  ui/src/pages/Alert/Event/index.tsx
  ui/src/pages/Alert/Rules/RuleDrawerForm.tsx
  ui/src/pages/Alert/Rules/index.tsx
  ui/src/pages/Alert/Shield/ShieldDrawerForm.tsx
  ui/src/pages/Alert/Shield/index.less
  ui/src/pages/Alert/Shield/index.tsx
  ui/src/pages/Login/index.tsx
  ui/src/pages/Tenant/Detail/Backup/BackupJobs.tsx
  ui/src/type/typings.d.ts
Labels: dashboard

#358 Fixed an issue where tenant monitoring charts were displayed abnormally in cluster details
  ui/package.json
  ui/src/api/generated/api.ts
  ui/src/api/generated/base.ts
  ui/src/api/index.ts
  ui/src/components/MonitorComp/LineGraph.tsx
  ui/src/components/MonitorComp/index.tsx
  ui/src/pages/Cluster/Detail/Tenant/index.tsx
  ui/src/services/index.ts
  ui/src/type/typings.d.ts
Labels: bug

#361 Feat:add the drawer component of the alarm channel
  ui/src/components/AlertDrawer/index.tsx
  ui/src/constants/index.ts
  ui/src/pages/Alert/Channel/ChannelDrawer.tsx
  ui/src/pages/Alert/Channel/index.tsx
  ui/src/pages/Alert/Shield/ShieldDrawerForm.tsx
  ui/src/type/alert.d.ts
Labels: dashboard

#364 Fix:resource verification depends on zone selection
  ui/src/components/customModal/ModifyUnitDetailModal.tsx
  ui/src/pages/Tenant/New/ResourcePools.tsx
  ui/src/pages/Tenant/helper.ts
Labels: bug

#362 Added documents for Storage Compatibility
  README-CN.md
  README.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-pages/index.mdx
  docsite/src/pages/index.mdx
Labels: documentation

#365 Add the function of creating new alarm push
  ui/src/components/InputLabel/index.less
  ui/src/components/InputLabel/index.tsx
  ui/src/pages/Alert/Channel/index.tsx
  ui/src/pages/Alert/Shield/ShieldDrawerForm.tsx
  ui/src/pages/Alert/Subscriptions/SubscripDrawerForm.tsx
  ui/src/pages/Alert/Subscriptions/index.less
  ui/src/pages/Alert/Subscriptions/index.tsx
Labels: dashboard

#369 Some details
  ui/mock/alertAPI.ts
  ui/src/pages/Alert/Channel/ChannelDrawer.tsx
  ui/src/pages/Alert/Channel/index.tsx
  ui/src/pages/Alert/Event/index.tsx
  ui/src/pages/Alert/Shield/ShieldDrawerForm.tsx
  ui/src/pages/Alert/Shield/index.tsx
  ui/src/pages/Alert/Subscriptions/SubscripDrawerForm.tsx
  ui/src/pages/Alert/index.less
  ui/src/pages/Alert/index.tsx
  ui/src/type/alert.d.ts
Labels: dashboard

#379 Added Quick Start for Dashboard; Replace OCP with Todo List
  README-CN.md
  README.md
  docsite/docs/dashboard/quickstart.mdx
  docsite/docs/manual/900.appendix/100.example.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/dashboard/quickstart.mdx
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/manual/900.appendix/100.example.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-pages/index.mdx
  docsite/src/pages/index.mdx
  docsite/static/img/dashboard/cluster-metrics.png
  docsite/static/img/dashboard/login.png
  docsite/static/img/dashboard/tenant-metrics.png
  example/webapp/mysql.yaml
  example/webapp/obproxy.yaml
  example/webapp/oceanbase-todo.yaml
  example/webapp/ocp.yaml
Labels: documentation

#393 Supports selecting shield objects when creating a shield
  ui/mock/alertAPI.ts
  ui/package.json
  ui/src/pages/Alert/AlarmFilter/index.tsx
  ui/src/pages/Alert/Channel/ChannelDrawer.tsx
  ui/src/pages/Alert/Rules/RuleDrawerForm.tsx
  ui/src/pages/Alert/Shield/ShieldDrawerForm.tsx
  ui/src/pages/Alert/Shield/ShieldObjInput.tsx
  ui/src/pages/Alert/Shield/index.tsx
  ui/src/pages/Alert/Subscriptions/SubscripDrawerForm.tsx
  ui/src/pages/Alert/helper.ts
  ui/src/pages/Alert/index.tsx
  ui/yarn.lock
Labels: dashboard

#402 Support editing functions of each module
  ui/config/config.ts
  ui/mock/alertAPI.ts
  ui/src/api/generated/api.ts
  ui/src/components/InputLabel/index.tsx
  ui/src/pages/Alert/AlarmFilter/index.tsx
  ui/src/pages/Alert/Rules/RuleDrawerForm.tsx
  ui/src/pages/Alert/Rules/index.tsx
  ui/src/pages/Alert/Shield/ShieldDrawerForm.tsx
  ui/src/pages/Alert/Shield/ShieldObjInput.tsx
  ui/src/pages/Alert/Shield/index.tsx
  ui/src/pages/Alert/helper.ts
  ui/src/type/alert.d.ts
Labels: dashboard

#403 Supports requesting data after modifying filter items
  ui/src/pages/Alert/AlarmFilter/index.tsx
  ui/src/pages/Alert/Event/index.tsx
  ui/src/pages/Alert/Rules/index.tsx
  ui/src/pages/Alert/Shield/index.tsx
Labels: dashboard

#409 Initialize proxy management module
  ui/config/routes.ts
  ui/mock/obproxyAPI.ts
  ui/src/api/index.ts
  ui/src/pages/Cluster/ClusterList.tsx
  ui/src/pages/Cluster/Detail/Overview/index.tsx
  ui/src/pages/Cluster/Detail/index.tsx
  ui/src/pages/Cluster/index.less
  ui/src/pages/Layouts/BasicLayout/index.tsx
  ui/src/pages/Layouts/DetailLayout/index.tsx
  ui/src/pages/OBProxy/ClusterList.tsx
  ui/src/pages/OBProxy/Detail/Monitor/index.tsx
  ui/src/pages/OBProxy/Detail/Overview/BasicInfo.tsx
  ui/src/pages/OBProxy/Detail/Overview/DetailConfig.tsx
  ui/src/pages/OBProxy/Detail/Overview/NodeInfo.tsx
  ui/src/pages/OBProxy/Detail/Overview/index.tsx
  ui/src/pages/OBProxy/Detail/index.tsx
  ui/src/pages/OBProxy/New/index.tsx
  ui/src/pages/OBProxy/index.tsx
  ui/src/pages/Tenant/Detail/index.tsx
  ui/src/type/typings.d.ts
Labels: dashboard

#414 Initialize the page for creating an obproxy cluster and handle some details
  ui/src/components/AlertDrawer/index.tsx
  ui/src/components/PreText/index.less
  ui/src/components/PreText/index.tsx
  ui/src/components/SelectNSFromItem/index.tsx
  ui/src/pages/Alert/Channel/ChannelDrawer.tsx
  ui/src/pages/Alert/Channel/index.less
  ui/src/pages/Alert/Channel/index.tsx
  ui/src/pages/Alert/Rules/index.tsx
  ui/src/pages/Alert/Shield/index.tsx
  ui/src/pages/Alert/Subscriptions/index.tsx
  ui/src/pages/Cluster/New/BasicInfo.tsx
  ui/src/pages/OBProxy/New/BasicConfig.tsx
  ui/src/pages/OBProxy/New/index.tsx
Labels: dashboard

#417 Support form submit for each module
  ui/config/config.ts
  ui/src/constants/index.ts
  ui/src/pages/Alert/AlarmFilter/index.tsx
  ui/src/pages/Alert/Channel/ChannelDrawer.tsx
  ui/src/pages/Alert/Channel/index.tsx
  ui/src/pages/Alert/Event/index.tsx
  ui/src/pages/Alert/Rules/RuleDrawerForm.tsx
  ui/src/pages/Alert/Rules/index.tsx
  ui/src/pages/Alert/Shield/ShieldDrawerForm.tsx
  ui/src/pages/Alert/Shield/index.tsx
  ui/src/pages/Alert/Subscriptions/SubscripDrawerForm.tsx
  ui/src/pages/Alert/Subscriptions/index.tsx
  ui/src/pages/Alert/helper.ts
  ui/src/pages/Layouts/BasicLayout/index.tsx
Labels: dashboard
