Repository oceanbase/ob-operator, pull requests merged in 2024-06, with the labels that each got.

#420 Dealing with some details
  ui/src/api/generated/api.ts
  ui/src/api/index.ts
  ui/src/constants/index.ts
  ui/src/pages/Alert/Channel/ChannelDrawer.tsx
  ui/src/pages/Alert/Event/index.tsx
  ui/src/pages/Alert/Rules/RuleDrawerForm.tsx
  ui/src/pages/Alert/Rules/index.tsx
  ui/src/pages/Alert/Shield/ShieldDrawerForm.tsx
  ui/src/pages/Alert/Shield/ShieldObjInput.tsx
  ui/src/pages/Alert/Shield/index.tsx
  ui/src/type/alert.d.ts
Labels: dashboard

#430 Some details
  ui/mock/alertAPI.ts
  ui/src/api/generated/api.ts
  ui/src/components/InputLabelComp/index.tsx
  ui/src/components/PreText/index.tsx
  ui/src/constants/index.ts
  ui/src/pages/Alert/AlarmFilter/index.tsx
  ui/src/pages/Alert/Channel/ChannelDrawer.tsx
  ui/src/pages/Alert/Event/index.tsx
  ui/src/pages/Alert/Rules/RuleDrawerForm.tsx
  ui/src/pages/Alert/Rules/index.tsx
  ui/src/pages/Alert/Shield/ShieldDrawerForm.tsx
  ui/src/pages/Alert/Shield/index.tsx
  ui/src/pages/Alert/Subscriptions/SubscripDrawerForm.tsx
  ui/src/pages/Alert/Subscriptions/index.tsx
  ui/src/pages/Alert/helper.ts
Labels: dashboard

#434 Add InputTimeComp and fix some bugs
  ui/src/components/InputTimeComp/index.tsx
  ui/src/pages/Alert/Channel/ChannelDrawer.tsx
  ui/src/pages/Alert/Channel/index.tsx
  ui/src/pages/Alert/Event/index.tsx
  ui/src/pages/Alert/Rules/RuleDrawerForm.tsx
  ui/src/pages/Alert/Rules/index.tsx
  ui/src/pages/Alert/Subscriptions/SubscripDrawerForm.tsx
  ui/src/pages/Alert/Subscriptions/index.tsx
Labels: dashboard

#441 Fixed patching obproxy parameters
  charts/oceanbase-dashboard/Chart.yaml
  internal/dashboard/business/obproxy/configmap.go
  internal/dashboard/business/obproxy/obproxy.go
  internal/dashboard/generated/swagger/docs.go
  internal/dashboard/generated/swagger/swagger.json
  internal/dashboard/generated/swagger/swagger.yaml
  internal/dashboard/model/obproxy/param.go
  scripts/connect.sh
Labels: dashboard

#443 Add help information
  ui/src/api/generated/api.ts
  ui/src/pages/Alert/Channel/ChannelDrawer.tsx
  ui/src/pages/Alert/Rules/RuleDrawerForm.tsx
  ui/src/pages/Alert/Shield/ShieldDrawerForm.tsx
  ui/src/pages/Alert/Subscriptions/SubscripDrawerForm.tsx
Labels: dashboard

#445 i18n
  ui/must.cjs
  ui/package.json
  ui/src/api/index.ts
  ui/src/components/AlertDrawer/index.tsx
  ui/src/components/InputLabelComp/index.tsx
  ui/src/components/InputTimeComp/index.tsx
  ui/src/constants/index.ts
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Alert/AlarmFilter/index.tsx
  ui/src/pages/Alert/Channel/ChannelDrawer.tsx
  ui/src/pages/Alert/Channel/index.tsx
  ui/src/pages/Alert/Event/index.tsx
  ui/src/pages/Alert/Rules/RuleDrawerForm.tsx
  ui/src/pages/Alert/Rules/index.tsx
  ui/src/pages/Alert/Shield/ShieldDrawerForm.tsx
  ui/src/pages/Alert/Shield/ShieldObjInput.tsx
  ui/src/pages/Alert/Shield/index.tsx
  ui/src/pages/Alert/Subscriptions/SubscripDrawerForm.tsx
  ui/src/pages/Alert/Subscriptions/index.tsx
  ui/src/pages/Alert/helper.ts
  ui/src/pages/Alert/index.tsx
  ui/src/pages/Layouts/BasicLayout/index.tsx
  ui/src/pages/Layouts/DetailLayout/index.tsx
  ui/src/pages/OBProxy/ClusterList.tsx
  ui/src/pages/OBProxy/Detail/Overview/BasicInfo.tsx
  ui/src/pages/OBProxy/Detail/Overview/DetailConfig.tsx
  ui/src/pages/OBProxy/Detail/Overview/NodeInfo.tsx
  ui/src/pages/OBProxy/Detail/Overview/index.tsx
  ui/src/pages/OBProxy/New/BasicConfig.tsx
  ui/src/pages/OBProxy/New/index.tsx
  ui/src/pages/Tenant/Detail/Overview/Backups.tsx
  ui/yarn.lock
Labels: dashboard

#452 Fix some bugs
  ui/src/i18n/strings/zh-CN.json
  ui/src/models/alarm.ts
  ui/src/pages/Alert/Rules/RuleDrawerForm.tsx
  ui/src/pages/Alert/Rules/index.tsx
  ui/src/pages/Alert/Shield/ShieldObjInput.tsx
  ui/src/pages/Alert/index.tsx
  ui/src/pages/Cluster/ClusterList.tsx
  ui/src/pages/Layouts/DetailLayout/index.tsx
Labels: bug

#455 Add monitoring to obproxy
  ui/.prettierrc
  ui/package.json
  ui/src/components/MonitorDetail/index.tsx
  ui/src/constants/index.ts
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Alert/AlarmFilter/index.tsx
  ui/src/pages/Cluster/Detail/Monitor/index.tsx
  ui/src/pages/Cluster/Detail/Tenant/index.tsx
  ui/src/pages/Cluster/index.tsx
  ui/src/pages/OBProxy/ClusterList.tsx
  ui/src/pages/OBProxy/Detail/Monitor/index.tsx
  ui/src/pages/OBProxy/Detail/Overview/BasicInfo.tsx
  ui/src/pages/OBProxy/Detail/Overview/ConfigDrawer.tsx
  ui/src/pages/OBProxy/Detail/Overview/DetailConfig.tsx
  ui/src/pages/OBProxy/Detail/Overview/index.tsx
  ui/src/pages/OBProxy/New/BasicConfig.tsx
  ui/src/pages/OBProxy/New/index.tsx
  ui/src/pages/OBProxy/index.tsx
  ui/src/pages/Tenant/index.tsx
  ui/src/services/index.ts
  ui/src/type/monitor.d.ts
  ui/src/type/obproxy.d.ts
  ui/src/type/typings.d.ts
Labels: dashboard

#454 Feature: integrate odc into dashboard connection module
  ui/src/api/generated/api.ts
  ui/src/pages/Cluster/Detail/Connection/index.tsx
  ui/src/pages/Tenant/Detail/Connection/index.tsx
Labels: dashboard

#461 fix bugs
  ui/src/components/InputTimeComp/index.tsx
  ui/src/pages/Alert/Event/index.tsx
  ui/src/pages/Alert/Rules/RuleDrawerForm.tsx
Labels: bug

#464 Resolve some problems of UI
  ui/config/config.ts
  ui/src/access.ts
  ui/src/app.tsx
  ui/src/components/customModal/showDeleteConfirm/index.tsx
  ui/src/pages/Alert/Subscriptions/SubscripDrawerForm.tsx
  ui/src/pages/Alert/Subscriptions/index.less
  ui/src/pages/OBProxy/Detail/Overview/DetailConfig.tsx
  ui/src/utils/helper.ts
Labels: bug

#466 fix:filter out empty parameter
  ui/src/pages/OBProxy/New/index.tsx
  ui/src/pages/OBProxy/helper.ts
Labels: bug

#468 Resole some bugs and optimize the code
  ui/mock/clusterAPI.ts
  ui/mock/obproxyAPI.ts
  ui/mock/tenantAPI.ts
  ui/src/components/EventsTable/index.tsx
  ui/src/pages/Alert/Shield/ShieldObjInput.tsx
  ui/src/pages/Alert/helper.ts
  ui/src/pages/Cluster/ClusterList.tsx
  ui/src/pages/Cluster/Detail/Connection/index.tsx
  ui/src/pages/Cluster/Detail/Overview/BasicInfo.tsx
  ui/src/pages/Cluster/Detail/Overview/ZoneTable.tsx
  ui/src/pages/Cluster/Detail/Overview/index.tsx
  ui/src/pages/Cluster/Detail/Tenant/index.tsx
  ui/src/pages/Cluster/New/BasicInfo.tsx
  ui/src/pages/Cluster/New/index.tsx
  ui/src/pages/Cluster/index.tsx
  ui/src/pages/OBProxy/ClusterList.tsx
  ui/src/pages/OBProxy/Detail/Overview/index.tsx
  ui/src/pages/OBProxy/index.tsx
  ui/src/pages/Overview/index.tsx
  ui/src/pages/Tenant/Detail/Backup/index.tsx
  ui/src/pages/Tenant/Detail/Connection/index.tsx
  ui/src/pages/Tenant/Detail/NewBackup/index.tsx
  ui/src/pages/Tenant/Detail/Overview/BasicInfo.tsx
  ui/src/pages/Tenant/Detail/Overview/index.tsx
  ui/src/pages/Tenant/TenantsList.tsx
  ui/src/pages/Tenant/index.tsx
Labels: dashboard

#472 Solve the problem of selecting masked objects
  ui/src/pages/Alert/Shield/ShieldObjInput.tsx
  ui/src/pages/Alert/helper.ts
  ui/src/pages/OBProxy/Detail/Overview/ConfigDrawer.tsx
Labels: bug, dashboard

#474 Refactor select component
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/src/pages/Alert/AlarmFilter/index.tsx
  ui/src/pages/Alert/Shield/ClusterSelect.tsx
  ui/src/pages/Alert/Shield/ServerSelect.tsx
  ui/src/pages/Alert/Shield/ShieldDrawerForm.tsx
  ui/src/pages/Alert/Shield/ShieldObjInput.tsx
  ui/src/pages/Alert/Shield/TenantSelect.tsx
  ui/src/pages/Alert/Subscriptions/SubscripDrawerForm.tsx
  ui/src/pages/Alert/helper.ts
  ui/src/pages/Cluster/Detail/Connection/index.tsx
  ui/src/pages/OBProxy/New/BasicConfig.tsx
  ui/src/pages/Tenant/Detail/Connection/index.tsx
Labels: dashboard
