Repository oceanbase/ob-operator, pull requests merged in 2024-09, with the labels that each got.

#543 Fixed some problems found in testing for dashboard 0.3.1
  internal/dashboard/business/oceanbase/obtenant.go
  internal/dashboard/business/oceanbase/obtenant_pool.go
  internal/dashboard/generated/bindata/bindata.go
  internal/dashboard/handler/ac_handler.go
  internal/dashboard/model/param/obtenant_param.go
  internal/dashboard/model/response/obtenant.go
Labels: dashboard

#548 Enrich contributor guidance and remove redun…
  docsite/docs/developer/contributor-guidance.md
  docsite/docs/developer/develop-locally.md
  docsite/docs/developer/development.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/developer/contributor-guidance.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/developer/develop-locally.md
  docsite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/developer/development.md
  docsite/static/img/controller-manager.jpg
  docsite/static/img/crd.jpg
Labels: documentation

#547 Fine-grained control of some permissions
  ui/src/components/NodeSelector/index.tsx
  ui/src/components/SelectNSFromItem/index.tsx
  ui/src/components/TopoComponent/helper.ts
  ui/src/components/customModal/HandleRoleModal.tsx
  ui/src/components/customModal/ModifyUnitDetailModal.tsx
  ui/src/constants/index.ts
  ui/src/pages/Alert/AlarmFilter/index.tsx
  ui/src/pages/Alert/Shield/index.tsx
  ui/src/pages/Alert/index.tsx
  ui/src/pages/Cluster/Detail/Overview/index.tsx
  ui/src/pages/Cluster/Detail/Tenant/index.tsx
  ui/src/pages/Cluster/New/BasicInfo.tsx
  ui/src/pages/Cluster/New/index.tsx
  ui/src/pages/Cluster/index.tsx
  ui/src/pages/OBProxy/index.tsx
  ui/src/pages/Tenant/Detail/Overview/Replicas.tsx
  ui/src/pages/Tenant/Detail/Overview/index.tsx
  ui/src/pages/Tenant/New/ResourcePools.tsx
  ui/src/pages/Tenant/index.tsx
Labels: bug, dashboard

#555 add Access Control role text and ContentWithQuestion
  ui/src/components/customModal/HandleRoleModal.tsx
  ui/src/constants/access.ts
  ui/src/i18n/strings/en-US.json
  ui/src/i18n/strings/zh-CN.json
  ui/yarn.lock
Labels: dashboard

#557 fix: access edit Modal ContentWithQuestion error and chaneg ac fu…
  ui/src/components/customModal/HandleRoleModal.tsx
  ui/src/constants/access.ts
  ui/src/i18n/strings/en-US.json
Labels: bug

#559 fix:permission select
  ui/src/components/SelectNSFromItem/index.tsx
  ui/src/components/customModal/HandleRoleModal.tsx
  ui/src/pages/Cluster/Detail/Overview/index.tsx
  ui/src/pages/Cluster/New/Observer.tsx
  ui/src/pages/Cluster/New/index.tsx
  ui/src/pages/Cluster/index.tsx
  ui/src/pages/OBProxy/index.tsx
  ui/src/pages/Tenant/index.tsx
Labels: dashboard

#561 fix：Monitor request adds labels
  ui/src/pages/Cluster/Detail/Tenant/index.tsx
Labels: bug

#563 Bump version of dashboard chart
  charts/oceanbase-dashboard/Chart.yaml
  make/dashboard.mk
Labels: dashboard

#566 improve Password verification rules
  ui/src/components/PasswordInput/index.tsx
  ui/src/components/customModal/HandleAccountModal.tsx
  ui/src/components/customModal/ModifyPasswordModal.tsx
  ui/src/components/customModal/ResetPwdModal.tsx
  ui/src/pages/Cluster/New/helper.ts
  ui/src/pages/OBProxy/New/BasicConfig.tsx
  ui/src/utils/index.tsx
Labels: bug, dashboard
